const books = [
  {
    isbn: "978-0143127741",
    category: "Fiction",
    title: "The Alchemist",
    author: "Paulo Coelho",
    rating: 4.7,
    edition: "25th Anniversary Edition",
    publish_year: 2015,
    publisher: "HarperOne",
    cover_pic: "https://upload.wikimedia.org/wikipedia/commons/c/c4/TheAlchemist.jpg",
    qty_in_stock: 25,
    min_threshold: 10,
    buy_price: 10.00,
    sell_price: 15.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b01",
    description: "A philosophical book about a shepherd named Santiago and his journey to find a treasure, teaching the importance of listening to one's heart and following one's dreams."
  },
  {
    isbn: "978-0451524935",
    category: "Classic Literature",
    title: "1984",
    author: "George Orwell",
    rating: 4.8,
    edition: "1st",
    publish_year: 1950,
    publisher: "Signet Classics",
    cover_pic: "https://coverart.oclc.org/ImageWebSvc/oclc/+-+4080960476_140.jpg",
    qty_in_stock: 72,
    min_threshold: 20,
    buy_price: 7.00,
    sell_price: 10.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b02",
    description: "A dystopian novel set in a totalitarian society under constant surveillance, exploring themes of government control, censorship, and individual freedom through the life of Winston Smith."
  },
  {
    isbn: "978-0316769488",
    category: "Fiction",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    rating: 4.3,
    edition: "1st",
    publish_year: 1951,
    publisher: "Little, Brown and Company",
    cover_pic: "https://coverart.oclc.org/ImageWebSvc/oclc/+-+91569287_140.jpg",
    qty_in_stock: 43,
    min_threshold: 10,
    buy_price: 9.00,
    sell_price: 14.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b01",
    description: "A novel about teenage rebellion and angst, narrated by the iconic character Holden Caulfield, who experiences the complexities of adolescence and the loss of innocence."
  },
  {
    isbn: "978-0316015844",
    category: "Fantasy",
    title: "Twilight",
    author: "Stephenie Meyer",
    rating: 4.6,
    edition: "1st",
    publish_year: 2005,
    publisher: "Little, Brown and Company",
    cover_pic: "https://coverart.oclc.org/ImageWebSvc/oclc/+-+19784620_140.jpg",
    qty_in_stock: 64,
    min_threshold: 10,
    buy_price: 12.00,
    sell_price: 18.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b03",
    description: "A vampire romance novel that tells the story of Bella Swan, a teenage girl who falls in love with Edward Cullen, a vampire, and navigates the dangers and complexities of their relationship."
  },
  {
    isbn: "978-0553573428",
    category: "Fantasy",
    title: "A Game of Thrones",
    author: "George R. R. Martin",
    rating: 4.8,
    edition: "1st",
    publish_year: 1996,
    publisher: "Bantam Books",
    cover_pic: "https://coverart.oclc.org/ImageWebSvc/oclc/+-+780112352_140.jpg",
    qty_in_stock: 82,
    min_threshold: 20,
    buy_price: 15.00,
    sell_price: 20.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b04",
    description: "The first book in the epic fantasy series 'A Song of Ice and Fire,' introducing a world of political intrigue, war, and the struggle for the Iron Throne in the land of Westeros."
  },
  {
    isbn: "978-0062316110",
    category: "Fiction",
    title: "The Goldfinch",
    author: "Donna Tartt",
    rating: 4.5,
    edition: "1st",
    publish_year: 2013,
    publisher: "Little, Brown and Company",
    cover_pic: "https://coverart.oclc.org/ImageWebSvc/oclc/+-+072649003_140.jpg",
    qty_in_stock: 49,
    min_threshold: 15,
    buy_price: 14.00,
    sell_price: 22.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b02",
    description: "A Pulitzer Prize-winning novel that follows the life of Theo Decker, whose mother dies in a terrorist attack at a museum, leaving him with a priceless painting and a life filled with pain and beauty."
  },
  {
    isbn: "978-0061120060",
    category: "Self-Help",
    title: "The Secret",
    author: "Rhonda Byrne",
    rating: 4.2,
    edition: "1st",
    publish_year: 2006,
    publisher: "Atria Books",
    cover_pic: "https://coverart.oclc.org/ImageWebSvc/oclc/+-+6599411156_140.jpg",
    qty_in_stock: 53,
    min_threshold: 10,
    buy_price: 11.00,
    sell_price: 17.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b03",
    description: "A self-help book that explores the law of attraction and how positive thinking can create life-changing results in areas such as health, wealth, and happiness."
  },
  {
    isbn: "978-0743273565",
    category: "Fiction",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    rating: 4.4,
    edition: "1st",
    publish_year: 1925,
    publisher: "Scribner",
    cover_pic: "https://coverart.oclc.org/ImageWebSvc/oclc/+-+1837119886_140.jpg",
    qty_in_stock: 71,
    min_threshold: 10,
    buy_price: 8.00,
    sell_price: 12.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b04",
    description: "A classic novel set in the Jazz Age, exploring themes of decadence, idealism, and social upheaval through the life and times of Jay Gatsby and his obsession with Daisy Buchanan."
  },
  {
    isbn: "978-0385751537",
    category: "Young Adult",
    title: "The Book Thief",
    author: "Markus Zusak",
    rating: 4.7,
    edition: "Reprint Edition",
    publish_year: 2007,
    publisher: "Knopf Books for Young Readers",
    cover_pic: "https://coverart.oclc.org/ImageWebSvc/oclc/+-+38434540_140.jpg",
    qty_in_stock: 58,
    min_threshold: 10,
    buy_price: 10.00,
    sell_price: 14.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b01",
    description: "A historical novel set in Nazi Germany, narrated by Death, that tells the story of a young girl named Liesel Meminger who finds solace in stealing books and sharing them with others."
  },
  {
    isbn: "978-1250214181",
    category: "Biography",
    title: "Becoming",
    author: "Michelle Obama",
    rating: 4.9,
    edition: "1st",
    publish_year: 2018,
    publisher: "Crown",
    cover_pic: "https://coverart.oclc.org/ImageWebSvc/oclc/+-+6708695856_140.jpg",
    qty_in_stock: 19,
    min_threshold: 15,
    buy_price: 15.00,
    sell_price: 25.00,
    vendor_id: "60d5ec49f5ee3e2ddca25b04",
    description: "A memoir by former First Lady Michelle Obama, detailing her experiences from childhood through her time in the White House, and sharing insights into her personal and professional life."
  }
];

module.exports = books;